title: Johann's Blog
email: johann.gerberding@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/johannsblog" # the subpath of your site, e.g. /blog
url: "johanngerberding.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  johanngerberding

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
   math_engine: mathjax
   html_to_native: true
   parse_block_html: true